import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    // ops/deploy-site.ps1 preserves the previous export here for one-command rollback.
    // It is build output like out/ and must never be linted or formatted.
    "out.prev/**",
    "build/**",
    "next-env.d.ts",

    // Vendored WordPress theme + plugin output. This is third-party (and largely
    // minified) code we deliberately never edit -- see CLAUDE.md §3 rule 4. Linting
    // it produced 16 errors and ~740 warnings from jQuery, magnific-popup, modernizr
    // and owl.carousel, which made `npm run lint` unusable as a build gate.
    "public/wp-content/**",
    "public/wp-includes/**",

    // Generated artifacts, regenerated by `npm run enrich`.
    "content/site.json",
    "content/enriched/_manifest.json",

    // Migration scratch dirs.
    ".scratch/**",
    ".scratch2/**",
    ".scratch3/**",
  ]),

  {
    // Authored page modules are data, not application code: each one is a single
    // `export default { ... }` object literal by design (see lib/enrich/types.ts).
    files: ["content/enriched/*.mjs"],
    rules: { "import/no-anonymous-default-export": "off" },
  },
]);

export default eslintConfig;
