/**
 * Repairs the internal links the WordPress source shipped broken, then fails the build if any
 * internal <a href> still points at a route the site does not generate.
 *
 * Three classes of breakage, all reported as 404s by the QA crawl:
 *   1. typos in hand-written hrefs (stray space, curly apostrophe, wrong slug) → remapped;
 *   2. links to WordPress archive routes that were never migrated (/author/…, /category/…)
 *      → unwrapped to plain text, since there is no destination to point them at;
 *   3. links to pages that simply did not exist → those pages are now generated by
 *      scripts/pages.mjs, so only the missing trailing slash has to be normalized here
 *      (next.config.ts sets trailingSlash: true, and the static export writes <route>/index.html).
 *
 * Runs last in `npm run snapshot` so it also sees the markup produced by scripts/enrich.mjs.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "node-html-parser";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const FILE = join(ROOT, "content", "site.json");

/** Broken href (decoded, no trailing slash) → the real route it meant. */
const REMAP = new Map([
  ["/services/שכפול-מפתח- מרצדס", "/services/שכפול-מפתח-מרצדס/"], // stray space inside the slug
  ["/services/שכפול-מפתח-פיג’ו", "/services/שכפול-מפתח-פיגו/"], // curly apostrophe, slug has none
  ["/services/שכפול-מפתח-לקיה", "/services/שכפול-מפתח-קיה/"], // slug is קיה, not לקיה
  ["/צור-קשר", "/contact/"], // never existed; the contact page lives at /contact/
]);

/** Link prefixes with no migrated destination — the anchor becomes plain text. */
const UNLINK = [/^\/author\//, /^\/category\//, /^\/tag\//];

const ASSET = /\.(png|jpe?g|gif|svg|webp|avif|ico|css|js|mjs|woff2?|ttf|eot|pdf|xml|txt|zip)$/i;
const NON_ROUTE = /^(tel:|mailto:|whatsapp:|sms:|javascript:|data:|#)/i;

const site = JSON.parse(readFileSync(FILE, "utf8"));

/** Every route the site generates, decoded and without its trailing slash ("" for the front page). */
const routes = new Set(site.pages.map((p) => p.segments.join("/")));

const decode = (s) => {
  try {
    return decodeURIComponent(s);
  } catch {
    return s;
  }
};

/** Split an href into its route key (decoded, no leading/trailing slash) + the suffix to keep. */
function routeOf(href) {
  const [beforeHash, hash = ""] = href.split("#");
  const [path, query = ""] = beforeHash.split("?");
  return {
    // Trimmed: some source hrefs carry a stray space before the closing slash.
    key: decode(path).replace(/^\/+|\/+$/g, "").trim(),
    suffix: (query ? `?${query}` : "") + (hash ? `#${hash}` : ""),
  };
}

let remapped = 0;
let slashed = 0;
let unlinked = 0;
const unresolved = [];

for (const page of site.pages) {
  const root = parse(page.bodyHtml, {
    blockTextElements: { script: true, style: true, noscript: true, pre: true },
  });
  let changed = false;

  for (const a of root.querySelectorAll("a[href]")) {
    const href = a.getAttribute("href") || "";
    if (!href || NON_ROUTE.test(href)) continue;
    // Absolute links to other hosts are out of scope; same-origin ones were made relative by scrape.mjs.
    if (/^[a-z][a-z0-9+.-]*:/i.test(href) || href.startsWith("//")) continue;
    if (!href.startsWith("/") || ASSET.test(href.split(/[?#]/)[0])) continue;

    const { key, suffix } = routeOf(href);

    const target = REMAP.get("/" + key);
    if (target) {
      a.setAttribute("href", target + suffix);
      remapped++;
      changed = true;
      continue;
    }

    if (UNLINK.some((re) => re.test("/" + key + "/"))) {
      a.replaceWith(`<span>${a.innerHTML}</span>`);
      unlinked++;
      changed = true;
      continue;
    }

    if (!routes.has(key)) {
      unresolved.push(`${decode(page.path)}  →  ${decode(href)}`);
      continue;
    }

    // Normalize to the trailing-slash form the static export actually writes.
    const canonical = (key ? `/${key}/` : "/") + suffix;
    if (href !== canonical && decode(href) !== canonical) {
      a.setAttribute("href", canonical);
      slashed++;
      changed = true;
    }
  }

  if (changed) page.bodyHtml = root.toString();
}

writeFileSync(FILE, JSON.stringify(site, null, 2), "utf8");
console.log(
  `fix-links: remapped ${remapped}, normalized ${slashed} trailing slash(es), unlinked ${unlinked} dead archive link(s).`,
);

if (unresolved.length) {
  const uniq = [...new Set(unresolved)];
  console.error(`\nBROKEN INTERNAL LINKS (${unresolved.length}, ${uniq.length} unique):`);
  for (const u of uniq) console.error("  ! " + u);
  process.exit(1);
}
